name: MacOS Release (Qt)

on: [workflow_dispatch, push]

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}/SerialTest
  QT_VERSION:   5.15.2
  ARTIFACT:     SerialTest.dmg

jobs:
  build:
    runs-on:  macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout SerialTest
        run: |
          git clone https://github.com/wh201906/SerialTest

      - name: Download QCustomPlot
        run: |
          wget https://www.qcustomplot.com/release/2.1.1/QCustomPlot-source.tar.gz
          tar -xzf QCustomPlot-source.tar.gz
          cp qcustomplot-source/qcustomplot.* SerialTest/src

      - name: Install Qt
        run: |
          wget -cq https://download.qt.io/official_releases/qt/5.15/5.15.5/single/qt-everywhere-opensource-src-5.15.5.tar.xz
          tar -xkf qt-everywhere-opensource-src-5.15.5.tar.xz
          mkdir qt5
          mkdir build
          cp patch/qiosurfacegraphicsbuffer.h qt-everywhere-src-5.15.5/src/plugins/platforms/cocoa/
          cd build
          ../qt-everywhere-src-5.15.5/configure --disable-rpath \
            -no-warnings-are-errors -prefix $(pwd)/../qt5 \
            -opensource -confirm-license -release -nomake examples -nomake tests \
            -no-compile-examples -no-feature-testlib -skip qt3d -skip qtactiveqt -skip \
            qtcanvas3d -skip qtcharts -skip qtdatavis3d -skip qtdeclarative -skip qtdoc \
            -skip qtgamepad -skip qtgraphicaleffects -skip qtmacextras -skip qtmultimedia \
            -skip qtnetworkauth -skip qtpurchasing -skip qtquickcontrols -skip qtquickcontrols2 \
            -skip qtremoteobjects -skip qtscxml -skip qtspeech -skip qtwayland -skip qtwebview \
            -skip qtwinextras -skip qtx11extras -skip qtwebengine -skip qtlocation -skip \
            qtlottie -skip qtquick3d -skip qtquicktimeline -skip qtscript -skip qtsensors \
            -skip qtserialbus -skip qttools -skip qtxmlpatterns -skip qtwebglplugin -skip \
            qtwebchannel -skip qtvirtualkeyboard -skip qttranslations
          make -j
          sudo make -j install

      - name: Show result
        run: |
          cd build
          ls -l
          cd ../qt5
          ls -l

      - name: Create build directory
        run:  mkdir ${{ runner.temp }}/shadow_build_dir

      - name: Build
        working-directory: ${{ runner.temp }}/shadow_build_dir
        run:  |
              export JOBS=$((`sysctl -n hw.ncpu`+1))
              ${{ github.workspace }}/qt5/bin/qmake -r ${SOURCE_DIR}/src/SerialTest.pro CONFIG+=app_bundle
              make -j$JOBS

      - name: Generate DMG file
        run: |
          ${{ github.workspace }}/qt5/bin/macdeployqt ${{ runner.temp }}/shadow_build_dir/SerialTest.app -dmg -verbose=2

      - name: Save artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}/shadow_build_dir/**/${{ env.ARTIFACT }}