name: Android Release

on: [workflow_dispatch, push]

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}/SerialTest

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout SerialTest
        run: |
          git clone https://github.com/wh201906/SerialTest

      - name: Download QCustomPlot
        run: |
          wget https://www.qcustomplot.com/release/2.1.1/QCustomPlot-source.tar.gz
          tar -xzf QCustomPlot-source.tar.gz
          cp qcustomplot-source/qcustomplot.* SerialTest/src

      - name: Install Qt
        run: |
          cat /etc/apt/sources.list
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y qt5-default qt5-default libqt5serialport5-dev qtconnectivity5-dev

      - name: Create build directory
        run:  mkdir ${{ runner.temp }}/shadow_build_dir

      - name: Build
        working-directory: ${{ runner.temp }}/shadow_build_dir
        run:  |
              export JOBS=$((`sysctl -n hw.ncpu`+1))
              qmake -r ${SOURCE_DIR}/src/SerialTest.pro
              make -j$JOBS apk_install_target
              androiddeployqt --release --output ./ --input android-SerialTest-deployment-settings.json

      - name: Show files
        working-directory: ${{ runner.temp }}/shadow_build_dir
        run: |
          ls -l
